### ISSUE TITLE
Use extra trajectories as additional runs

### ISSUE THREAD

**Issue by greenTara** [ag-csw/LDStreamHMMLearn#28]
We are not using our simulated data to the fullest extent. For instance, when doing the eta heatmap we only use half of the trajectories, because num_trajectories is the mid value. We could repeat the calculation on the other half of the trajectories, and treat this as another run, with the same model. This should help our expectations converge, with little extra time required.

**Comment by alexlafleur** [comment]
We had the idea to simulate the complete data, and use slices of that data for each of the runs, but we did not finish that up so that the code for that is incomplete and throwing errors. What we have is this:

```python
if j == 0:
      self.mm1_0_0 = self.mmf1_0.sample()[0]
      self.simulated_data = simulate_and_store(qmm1_0_0=self.mm1_0_0)
      simulated_data_ndarray = np.asarray(self.simulated_data)

num_trajs = np.shape(simulated_data_ndarray)[0]
simulated_data_slice = np.split(simulated_data_ndarray[j].flatten(), num_trajs ) # <--- Throws Error "array split does not result in equal division"
```
`simulated_data_ndarray` is of shape (16, ~4000). If the take `simulated_data_ndarray[j]` that would be a 1-d array of length ~4000 and by flattening that we get a 1-d array, too. So that makes no sense at that point.

Maybe we want to do something like this?
```
simulated_data_slice = np.split(simulated_data_ndarray.flatten(), num_trajs ) # Should result in 16 splits of the orginal array
evaluate.test_taumeta_eta(mm1_0_0=self.mm1_0_0, simulated_data=simulated_data_slice[j]) # And we take the j'th split of that.
```
