### ISSUE TITLE
Error Normal Probability Plot

### ISSUE THREAD

**Issue by alexlafleur** [ag-csw/LDStreamHMMLearn#5]
# Probability Plot

(with log error values)
![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19194817/4b7f2c30-8caf-11e6-8425-2f2219713bd0.png)

**Comment by alexlafleur** [comment]
# Probability Plot with Log Error Values

![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19149034/21d85996-8bc0-11e6-9b12-970d93c0485a.png)

**Comment by greenTara** [comment]
Can the plot call parameters be adjusted so that it shows sample quantiles
vs. theoretical quantiles instead of ordered values vs. theoretical
quantiles?

On Thu, Oct 6, 2016 at 6:26 AM, Alexandra La Fleur <notifications@github.com

**Comment by alexlafleur** [comment]
I did not find a solution for this using the scipy probplot function. But I found one in statsmodels.api which should do this. 
The returned plot looks like this:
![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19151474/28c1f69c-8bcd-11e6-8a9c-d3aae9ee5045.png)

Is this expected? 
The documentation of qqplot can be found [here](http://statsmodels.sourceforge.net/devel/generated/statsmodels.graphics.gofplots.qqplot.html)

**Comment by greenTara** [comment]
It looks like this plotting routine requires the distribution to be
manually adjusted to have mean of zero and standard deviation of one. So
that's not particularly convenient. So Let's go back to the other plotting
routine.

I believe the large deviation from normality is because there is an upper
bound to how large the error can be, because we are taking the difference
of two probability matrices. Probably the log transformation exaggerated
this situation.

 If this is true, then the deviation from normality on that side should get
smaller when the error is smaller, overall. Let's change the parameters for
making this plot so that is the case. For that to happen, we need each
estimate to get more information, so nwindow should be larger while the
model parameters stay the same.

On Thu, Oct 6, 2016 at 8:01 AM, Alexandra La Fleur <notifications@github.com

**Comment by alexlafleur** [comment]
## nwindow = 128 * nstep
![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19154648/b01fc71e-8bdb-11e6-94fc-7bf0df55f906.png)

## nwindow = 256 * nstep
![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19154611/851be25a-8bdb-11e6-902f-d474e1fc8622.png)

## nwindow = 512 * nstep
![error_probplot](https://cloud.githubusercontent.com/assets/4387137/19154714/f9b10d70-8bdb-11e6-9c86-152cf5ad61bb.png)

**Comment by greenTara** [comment]
Something fishy is going on. These errors are actually quite small (the
logs are large negative). So my original conjecture is not correct.

The deviant value seems to always be 0 Can we track down that value in the
original data to see where it is coming from?

On Thu, Oct 6, 2016 at 9:46 AM, Alexandra La Fleur <notifications@github.com

**Comment by alexlafleur** [comment]
Here is an examplary output for one probplot.

The log error values:
[ 0.01099288 -6.52967943 -6.53443875 ..., -6.81667353 -6.82836538
 -6.8028449 ]

the returned tuple of theoretical quantiles (osm, or order statistic medians) and ordered responses (osr):
((array([-3.20470173, -2.94003439, -2.79237406, ...,  2.79237406,
        2.94003439,  3.20470173]),
 array([-7.33290068, -7.32422428, -7.31605851, ..., -6.4290984 ,
       -6.38958126,  0.01099288])), 

and slope, intercept, r (is the square root of the coefficient of determination)
(0.22021052769786187, -6.8871614146309641, 0.74379305663073947))

**Comment by greenTara** [comment]
There is no text here, only plots. Can this issue be closed?

**Comment by alexlafleur** [comment]
Yes, the probability plots that can be used for the paper are in issue https://github.com/ag-csw/LDStreamHMMLearn/issues/14
